apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.nehaad.com.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html/;
        index index.html index.htm index.nginx-debian.html;

        server_name nginx.nehaad.com;

        location / {
                try_files $uri $uri/ =404;
        }
    }