version: '3'
services:

  front:
    image: nginx:1.17
    volumes:
      - /home/docker_sources/wordpress/nginx/cond.d:/etc/nginx/conf.d
    ports: 
      - 80:80

  php:
    image: php:7.3-fpm
    volumes:
      - /home/docker_files/wordpress/source_code:/var/www/html 
