version: '3'
services:

  portainer_app:
    image: portainer/portainer
    volumes:
      - /home/docker_files/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000

  wp_mysql_server:
    image: mysql:8
    volumes:
      - /home/docker_files/wordpress/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Jdfj@dki4456f
    deploy:
      mode: replicated
      replicas: 1
      labels: [MYSQL=wp]
      placement:
        constraints: [node.role == worker]

  wp_php:
    build: ./php-fpm
    volumes:
      - /home/docker_files/wordpress/source_code:/var/www/html
      - /home/docker_sources/wordpress/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d
      - /home/docker_sources/wordpress/php-fpm/php.d:/usr/local/etc/php
    depends_on:
      - wp_mysql_server
    environment:
      - MYSQL_HOST=wp_mysql_server
      - MYSQL_DB=wp_db
      - MYSQL_USER=wp_user
      - MYSQL_PASSWD=fkgj@44gb5
    deploy:
      mode: replicated
      replicas: 3
      labels: [PHP-FPM=wp]
      placement:
        constraints: [node.role == worker]

  wp_front:
    image: nginx:1.17
    volumes:
      - /home/docker_sources/wordpress/nginx/cond.d:/etc/nginx/conf.d
      - /home/docker_files/wordpress/source_code:/var/www/html
    ports: 
      - 80:80
    depends_on:
      - wp_php
    deploy:
      mode: replicated
      replicas: 4
      labels: [NGINX=wp]
